services:
  node-app:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    # build: .
    build:
      context: .
      args:
        NODE_ENV: development
      # target: production
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_USER=sanjeev
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    env_file:
      - ./.env
    command: npm run dev # for development
    # command: node index.js # for production
    restart: "no" # no | always | on-failure | unless-stopped
    depends_on:
      - mongo

  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db: